feat: add sessions page
GoCon/2024 pull request #15
Opened 2024-03-24 14:05 UTC by NozomuIkuta

[GOCON2024-47](https://gophersjp.backlog.com/view/GOCON2024-47)を実装しました。

2024-04-18 12:31 UTC, sago35 requested changes
横幅が小さくなった時に改行されるようになって欲しい。
Figma でいう所の 1024 px よりも小さいあたり。

![image](https://github.com/GoCon/2024/assets/9251039/dfcf9445-e719-4099-acff-06421511098b)

2024-04-22 10:09 UTC, sago35 commented
クリックしたら詳細ページに飛んでほしい (Sponsors と同じ感じ)

2024-05-06 09:46 UTC, sago35 commented
/sessions は良さそう。
残り、 /sessions/[id] のページが出来たらマージできそう。

2024-05-12 15:06 UTC, NozomuIkuta commented on package.json
> +    "@astropub/md": "^0.4.0",
Sessionのディスクリプションにマークダウンを使っている方がいたので導入しました。Astroの公式ページを見たところ、`.md` ファイル以外の任意の文字列をマークダウンとしてレンダリングするコンポーネントは提供されていないようです。

https://docs.astro.build/en/guides/markdown-content/

2024-05-12 15:07 UTC, NozomuIkuta commented on src/components/Session.astro
> +    }
色指定が知りたいです。

2024-05-12 15:08 UTC, NozomuIkuta commented on src/components/Session.astro
> +    </div>
GoCon 2023のサイトではTwitterへのリンクがありますが、今回のスピーカー情報には見当たらなかったので入れていません。どこかにまとまっていますか？

https://sessionize.com/api/v2/3xsxwh64/view/Speakers

2024-05-12 15:09 UTC, NozomuIkuta commented on src/pages/sessions/index.astro
> +  }
このあたりのpaddingの収縮具合は、画面が小さい時に大きい気がしたので雰囲気で縮めています。よしなに変更お願いします。

2024-05-12 15:10 UTC, NozomuIkuta commented on src/pages/sessions/[id].astro
> +  }
このあたりのpaddingの収縮具合は、画面が小さい時に大きい気がしたので雰囲気で縮めています。よしなに変更お願いします。

2024-05-12 15:10 UTC, NozomuIkuta commented on src/components/Session.astro
> +---
このコンポーネントのデザインは、原則GoCon 2023のものを踏襲しています。
変更すべき箇所があればお知らせください。

例：https://gocon.jp/2023/sessions/A1-SP/

2024-05-13 00:58 UTC, budougumi0617 approved these changes
偉業…!!

スッキリしていてとてもいいですね！！
syntax highrightとかリンクもちゃんとできてそうでした。
スピーカープロフィールもいい感じ。
一覧がレスポンシブになっているのも確認しました。

2024-05-13 01:57 UTC, Hiroya3 commented on src/components/Session.astro
> +    </div>
@NozomuIkuta 
session班のteruiです。

実装ありがとうございます！
SessionizeのAPIでX(twitter)のリンクを返していなかったので、設定変更して新たに返すようにしようと思いますが、
いかがでしょうか？（jsonが増えるので修正必要になってしまいますが）
<img width="419" alt="image" src="https://github.com/GoCon/2024/assets/29178256/025d0103-b550-4042-8add-bb8fe55dbcc1">

2024-05-13 02:00 UTC, NozomuIkuta commented on src/components/Session.astro
> +    </div>
@Hiroya3 
JSONの修正もデザイン追加もそんなに大変じゃないので、情報があれば表示します🙋‍♂️

2024-05-13 02:09 UTC, Hiroya3 commented on src/components/Session.astro
> +    </div>
@NozomuIkuta 
```
"links": [
      {
        "title": "Twitter",
        "url": "https://twitter.com/haruyama480",
        "linkType": "Twitter"
      }
    ],
```

linksフィールドが追加され以下のように返るようになりました！ 🙏

2024-05-13 05:40 UTC, NozomuIkuta commented on src/components/Session.astro
> +    </div>
@Hiroya3 

Twitterのリンクを追加しました: 87370c6

2024-05-13 06:00 UTC, Hiroya3 commented on src/components/Session.astro
> +    </div>
ありがとうございます！

2024-05-13 10:05 UTC, sago35 commented on src/components/Session.astro
> +    }
いったんこのまま行きましょう。

2024-05-13 10:05 UTC, sago35 commented on src/pages/sessions/index.astro
> +  }
今のままで良いと思います。

2024-05-13 10:06 UTC, sago35 commented on src/components/Session.astro
> +---
今のままで良いと思います。

2024-05-13 10:07 UTC, sago35 approved these changes
LGTM

2024-05-13 10:20 UTC, merged

2024-05-13 10:20 UTC, sago35 commented
LGTM
マージしました。

2024-06-01 01:27 UTC, sago35 commented
Session data は以下を参照。
https://goconjp.slack.com/archives/C06D7KCNQGZ/p1713781842987789