Staff 一覧ページを作成
GoCon/2024 pull request #4
Opened 2024-02-25 03:01 UTC by sago35

2023 を参考にある程度作りました。
が、 `@mui/icons-material/Twitter` とかを使ったレンダリングは力尽きたのでいったんテキストになっています。

以下からアクセスできます。

* /staff
  * http://localhost:4321/staff/

![image](https://github.com/GoCon/2024/assets/9251039/8fb825aa-9aa7-4fdd-b148-3587897f20d8)

2024-03-02 00:33 UTC, sago35 commented
Header の PR を参考に CSS 追加して ICON 表示することが出来ました。
いったん完成？

![image](https://github.com/GoCon/2024/assets/9251039/6c571bd8-e4b6-46f7-8b10-807342a444ae)

2024-03-02 01:37 UTC, budougumi0617 approved these changes
LGTM!よさそう！
ちなみに #5 の変更が入ったあとはlocalだと `http://localhost:4321/2024` がTOPになります 🙏 
```
$ pnpm dev

> gocon2024@0.0.1 dev /Users/budougumi0617/go/src/github.com/GoCon/2024
> astro dev


 astro  v4.2.3 ready in 67 ms

┃ Local    http://localhost:4321/2024
┃ Network  use --host to expose

10:35:13 watching for file changes...
10:35:30 [200] / 6ms
10:35:35 [200] /staff 9ms
```

2024-03-02 07:58 UTC, hytkgami requested changes

2024-03-02 07:58 UTC, hytkgami commented on src/content/config.ts
> +      otherLink: z.string(),
こちらのほうがより厳密で良いと思います！
```suggestion
      otherLink: z.string().url(),
```

2024-03-02 07:58 UTC, hytkgami commented on src/content/config.ts
> +      icon: z.string(),
こちらもおそらくアセットのURLを登録していくことになると思うので、URLでお願いします！
好みですがキー名はサムネイルでも良いかなと思いました 🙆‍♂️ 
```suggestion
     thumbnail: z.string().url(),
```

2024-03-02 07:58 UTC, hytkgami commented on src/content/config.ts
> +      githubLink: z.string(),
この2つはIDだけを入稿して、URLはViewで生成で良いと思います 🙆‍♂️ 
```suggestion
      twitterId: z.string(),
      githubId: z.string(),
```

2024-03-02 07:58 UTC, hytkgami commented on src/components/Staff.astro
> +                  </svg>
#6 では扱うアイコンの数が少なくてViewファイルに直接定義してしまったのですが、このコンポーネントではいくつかアイコンがあるので、`src/assets/icons/`などのパスを切って、そこに`ic_twitter.svg`などという名前で保存しておいてもらえると嬉しいです！

そうするとコードがスッキリするのと、GitHubのDiffで画像が出てくるのでメリットがあると思います 🙆‍♂️

2024-03-04 10:51 UTC, sago35 commented on src/content/config.ts
> +      githubLink: z.string(),
その形にします。

2024-03-04 12:13 UTC, sago35 commented
だいたい出来た感じがするけど、 svg への参照を `<Image src={ xxx } />` でしていると BASE_URL の影響で参照パスがずれますね。これは条件文気を astro.config.mjs に足す感じなのか何なのか、という所。

ChatGPT には以下のような提案を受けた。
NODE_ENV ではない何らかの設定にしておくとよさそうではあるけどどうなんでしょ？

```
import { defineConfig } from "astro/config";

const base = process.env.NODE_ENV === 'production' ? '/2024' : '/';

export default defineConfig({
  site: "https://gocon.github.io",
  base: base,
  i18n: {
    defaultLocale: "ja",
    locales: ["ja"],
    routing: {
      prefixDefaultLocale: false,
    },
  },
});
```

2024-03-04 14:16 UTC, sago35 commented
とりあえず分岐させてみた。
動いてそう。

https://github.com/GoCon/2024/blob/7adc01945bfcf133ddd26b610113fb69fd8b314f/astro.config.mjs#L3-L8

placehold ( https://placehold.jp/640x360.png ) は現在 503 なので表示できない模様。

![image](https://github.com/GoCon/2024/assets/9251039/94ac28a3-7baf-47b2-9de6-3a8918fc6d2f)

2024-03-04 14:16 UTC, sago35 commented on src/components/Staff.astro
> +                  </svg>
対応しました。

2024-03-10 07:22 UTC, hytkgami commented on astro.config.mjs
> +const base = import.meta.env.BASE_URL === "/" ? "/" : "/2024";
`import.meta.env.BASE_URL`がbaseオプションによって決まるので、意図しない結果になるような気がします 🤔

2024-03-10 07:22 UTC, hytkgami commented on package.json
> +    "sharp": "^0.33.2",
Astro Imageを使っているのでsharpパッケージは不要な気もするんですが、必要でしたか？ 🙋

2024-03-11 10:16 UTC, sago35 commented on astro.config.mjs
> +const base = import.meta.env.BASE_URL === "/" ? "/" : "/2024";
ペライチに合わせて修正予定 (revert 予定) です。

2024-03-18 10:34 UTC, sago35 commented on package.json
> +    "sharp": "^0.33.2",
Netlify のビルドでこけるので追加しました。

2024-04-22 10:21 UTC, sago35 commented
いったん閉じます。
別途作成しましょう。

2024-04-22 10:21 UTC, closed without merging