ペライチを作成
GoCon/2024 pull request #7
Opened 2024-03-04 16:04 UTC by sago35

色々と問題がありそうですが、いったん作成しました。

2024-03-04 16:08 UTC, sago35 commented
いったんこんな感じ。

![image](https://github.com/GoCon/2024/assets/9251039/d5caa099-02d5-4406-9b5b-c87741082a8d)

2024-03-07 05:25 UTC, budougumi0617 reviewed
設定のところが少し気になりました！

2024-03-07 05:25 UTC, budougumi0617 commented on astro.config.mjs
> +  base: base,
こうしないとどこか動かないとかありました 👀 ？
ここの値が `import.meta.env.BASE_URL` になるので、元のままのほうがいいかなと思いました（循環参照的になる？）

2024-03-07 05:25 UTC, budougumi0617 commented on src/pages/index.astro
> +  <div class="conference-announcement">
ありがとうございます！！！
スッキリしていていいですね！！

2024-03-07 12:23 UTC, sago35 commented
指摘対応完了しました。
また、地図の縮尺を広域側に少し変更、 Header 内リンクを修正しました。

2024-03-09 00:06 UTC, budougumi0617 approved these changes
よさそう！！LGTM!!

2024-03-10 07:38 UTC, hytkgami requested changes
幅1076px未満からレイアウトが崩れてしまうようなので、見直したいです！

![image](https://github.com/GoCon/2024/assets/8655384/743c9c85-caa2-4840-bc69-62c1b8e0d117)

2024-03-10 07:38 UTC, hytkgami commented on src/components/Footer/index.astro
> +  @media (max-width: 800px) {
ブレークポイントがヘッダーと異なるので、揃えておきたいです！

2024-03-10 07:38 UTC, hytkgami commented on src/components/Footer/index.astro
要素感の余白が狭くて情報のまとまりが分かりづらいので修正したいです！

![image](https://github.com/GoCon/2024/assets/8655384/8630ea58-f7f2-435f-a17c-5b63eeb48ec4)

2024-03-10 07:38 UTC, hytkgami commented on src/components/Header/index.astro
> +        ><Image
画像を入れたことでナビゲーション要素とロゴの水平軸が揃わなくなってしまったので、中央揃えにしたいです！

![image](https://github.com/GoCon/2024/assets/8655384/0d468b5b-0258-498b-a82b-a67b918235fc)

2024-03-11 10:10 UTC, sago35 commented on src/components/Footer/index.astro
現在の 2023 はこんな感じ

![image](https://github.com/GoCon/2024/assets/9251039/a988069f-03fd-4bc6-bcfe-74baba48dd37)

2024-03-11 10:10 UTC, sago35 commented on src/components/Header/index.astro
> +        ><Image
align 的な何かを足す。

2024-03-11 11:13 UTC, sago35 commented on src/components/Header/index.astro
> +        ><Image
img { display: block; } でそろいました。
![image](https://github.com/GoCon/2024/assets/9251039/f68626aa-9039-4a83-8f72-6d7c5cef0a93)

2024-03-11 11:14 UTC, sago35 commented on src/components/Footer/index.astro
> +  @media (max-width: 800px) {
768px にしたら大丈夫でした。

2024-03-11 12:28 UTC, sago35 commented on src/components/Header/index.astro
> +        ><Image
修正しました。

2024-03-11 12:30 UTC, sago35 commented on src/components/Footer/index.astro
> +  @media (max-width: 800px) {
という事で修正済みです。

2024-03-11 12:31 UTC, sago35 commented
ということでだいぶ良くなったはず。
とても学びが多い。

2024-03-11 13:01 UTC, hytkgami approved these changes

2024-03-11 13:01 UTC, merged